config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy"

  resources :users
  resources :boats do
    resources :jobs
    resources :userfollowships
  end

end

app/models/boat.rb
class Boat < ActiveRecord::Base
  validates :name, uniqueness: true
  belongs_to :user, dependent: :destroy
  has_many :jobs
  has_many :userfollowships
  has_many :followed_by, through: :userfollowships, source: :user
  has_attached_file :avatar, :styles =>
  { :medium => "300x300>", :thumb => "100x100>" },
  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar,
  :content_type => /\Aimage\/.*\Z/
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :name, uniqueness: true
  belongs_to :boat, dependent: :destroy
  validates :cargo, length: {in: 50..10000}
  validates_numericality_of :cost, :greater_than => 1000, :less_than => 100000000
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :boats
	has_many :userfollowships
	has_many :follows, through: :userfollowships, source: :boat
end

app/models/userfollowship.rb
class Userfollowship < ActiveRecord::Base
  belongs_to :user
  belongs_to :boat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]	
  end
  
  
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
	def index
		@boats = Boat.all
		# @follows = current_user.userfollowships.create(userfollowships_path)
	end
	def show
		@boats = Boat.find(params[:id])
		@job = Job.where(boat_id: params[:id])
	end
	def new
		@follow = User.find(current_user).follows
		@boat = Boat.new
		if current_user
		@boats = current_user.boats
		else
		redirect_to log_in_path
		end
	end

	def create
		# @boat = Boat.create(boat_params)
		# redirect_to @boat
		@boat = current_user.boats.new(boat_params)
		if @boat.save
			redirect_to new_boat_path
		else
			flash[:notice] = "Another boat has the same name, try again.."
			 redirect_to new_boat_path
		end
	end

	private
	def boat_params
	params.require(:boat).permit(:name, :max_containers, :current_location, :avatar)
	end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def new
		@boat = Boat.find(params[:boat_id])
		@job = @boat.jobs.new
	end

	def create
		@boat = Boat.find(params[:boat_id])
		@job = @boat.jobs.create(job_params)
		@boat.user = current_user
		if @job.save
		redirect_to boat_path(@boat)
		else
		flash[:notice] = "Job name already taken"
		flash[:notice1] = "Cost must be above $1000"
		flash[:notice2] = "Cargo description must be at least 50 characters"
		redirect_to new_boat_job_path(@boat)
	end
	end

	private
	def job_params
		params.require(:job).permit(:name, :containers_needed, :cargo, :cost, :origin, :destination)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		@user = User.new
	end
	def create
		@user = User.where(username: params[:username]).first
		if @user && @user.authenticate(params[:password])
			session[:user_id] = @user.id
			redirect_to @user
		else
			redirect_to root_path
		end
	end
	def destroy
		session.clear
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/userfollowships_controller.rb
class UserfollowshipsController < ApplicationController

	def index
		@boats = Boat.all
	end

	def new
		@boat = Boat.find(params[:boat_id])
		@follow = Userfollowship.new
	end

	def create
		@boat = Boat.find(params[:boat_id])
		@follow = @boat.userfollowships.new(userfollowship_params)
		@follow.save
		
		respond_to do |format|
      if @follow.save
        format.html { redirect_to new_boat_path, notice: 'Follow was successfully created.' }
        format.js { render :index }
      end
    end


	end

	private
	def userfollowship_params
		params.require(:userfollowship).permit(:user_id, :boat_id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
    current_user
  end
  def new
  	@user = User.new
  end
  def create
  	@user = User.create(user_params)
    session[:user_id] = @user.id
  	redirect_to @user
  end

	private
	def user_params
		params.require(:user).permit(:name, :username, :password)
	end	 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/userfollowships_helper.rb
module UserfollowshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boats/index.html.erb
<h1>ALL BOATS</h1>
<% @boats.each do |boat1| %>
<br>
<div id="boat_container1">
	<h2>Boat Name: <%= boat1.name %></h2>
	<h3>Boat's Photo:<br> <%= image_tag boat1.avatar(:medium), class: "boat_img1" %></h3>
</div>
<% end %>

<%= link_to "Follow User", boat_path(@follows), method: :post %>

app/views/boats/new.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<h1 id="center">Welcome <%= current_user.name.capitalize %>!
</h1>

<div id="container1">

	<div id="addboat1">

		<h1>Add a New Boat:</h1>
		<%= form_for @boat, :url => boats_path, :html => { :multipart => true } do |f| %>
		<%= f.label :name %><br>
		<%= f.text_field :name %><br>
		<%= f.label :max_containers %><br>
		<%= f.text_field :max_containers %><br><br>
		<%= f.label :current_location %><br>
		<%= f.select :current_location, [['Hong Kong'], ['Japan'], ['Brazil'], ['Singapore'], ['Italy']] %><br><br>
		<%= f.label "Add Boat Photo:" %>
		<%= f.file_field :avatar %><br><br>
		<%= f.submit "Submit" %>
		<% end %>

		<h1>Boats You're Following: </h1>
		<% @follow.each do |f| %>
		<h2><%= f.name %></h2>
		<%= image_tag f.avatar(:thumb) %>
		<%end %>

	</div>

	<div id="manageboat1">
		<h1>Boats You're Managing: </h1>
		<% @boats.each do |b| %>
		Boat's Name: <%= b.name %><br>
		Maximum # of Containers: <%= b.max_containers %><br>
		Boat's Current Location: <%= b.current_location %><br>
		Boat's Photo:<br> <%= image_tag b.avatar(:medium), class: "boat_img1" %><br><br>
		<%= link_to "Manage Boat's Jobs", boat_path(b) %>
		<hr>
		<% end %>
	</div>

</div>

app/views/boats/show.html.erb
<div id="container2">
<h1 id="center"><%= @boats.name.capitalize %>'s Information</h1>
<div id="boatinfo1">
<h1>Manage Current Boat:</h1>
Boat's Name: <%= @boats.name %><br>
Maximum # of Containers: <%= @boats.max_containers %><br>
Boat's Current Location: <%= @boats.current_location %><br>
Boat's Photo: <%= image_tag @boats.avatar(:medium) %><br>
<%= link_to "Assign New Job", new_boat_job_path(@boats)%>
</div>
<div id="jobinfo1">
<h1>Current Jobs Assigned:</h1>
<% @job.each do |j| %>
Job's Name: <%= j.name %><br>
Containers Required: <%= j.containers_needed %><br>
Job's Cargo: <%= j.cargo %><br>
Job's Cost: $<%= j.cost.to_i %><br>
Job's Origin: <%= j.origin %><br>
Job's Destination: <%= j.destination %><br><hr>
<% end %>
</div>
</div>

app/views/jobs/new.html.erb
<% if flash[:notice] %>
    <div class="notice">
    <%= flash[:notice] %><br>
    <%= flash[:notice1] %><br>
    <%= flash[:notice2] %><br>
    </div>
  <% end %>
<div id="assign1"><h1>Assign Job to: <%= @boat.name.capitalize %></h1>
<%= form_for [@boat,@job] do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name, :class => "input2" %><br>
<%= f.label :containers_needed %><br>
<%= f.text_field :containers_needed %><br>
<%= f.label :cargo %><br>
<%= f.text_area :cargo %><br>
<%= f.label :cost %><br>
<%= f.text_field :cost %><br><br>
<%= f.label :origin %><br>
<%= f.select :origin, [['Hong Kong'], ['Japan'], ['Brazil'], ['Singapore'], ['Italy']] %><br><br>
<%= f.label :destination %><br>
<%= f.select :destination, [['Greece'], ['England'], ['Beijing'], ['Korea'], ['Mexico']] %><br><br>
<%= f.submit "Assign Job" %>
<% end %>
</div>

app/views/jobs/show.html.erb
<h1>hello</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShippedApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<nav class="thing4">
		<ul class="thing3">
			<li class="thing2"><%= link_to "Home", root_path, :class => "thing5" %></li>
			<li class="thing2"><%= link_to "Manage Boats", new_boat_path, :class => "thing5" %></li>
			<li class="thing2"><%= link_to "Follow Boats", "/boats/boat_id/userfollowships", :class => "thing5" %></li>
			<li class="thing2"><%= link_to "Log Out", log_out_path, :class => "thing5" %></li>
		</ul>
	</nav>
</header>
<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/home.html.erb
<div id="splash1">
	<h1 id="center">Welcome to Ship App</h1>
	<div id="splash">

	</div>

	<div id="splash_button"><button class="splash_button2"><%= link_to "Sign Up", new_user_path, :class => "thing5" %></button class="splash_button2">
		<button class="splash_button2"><%= link_to "Log In", log_in_path, :class => "thing5" %></button class="splash_button2"></div>
</div>

app/views/userfollowships/_product.html.erb
<h1>HELLO!</h1>
<h1>Congratulations you have followed this boat</h1>
<h2>Click on follow boats to follow more</h2>

app/views/userfollowships/index.html.erb
<h1>Hello</h1>
<% @boats.each do |b| %>
<p><%= b.name %>
<%= link_to "Follow this Boat", new_boat_userfollowship_path(b) %> 
<br></p>
<% end %>

app/views/userfollowships/index.js.erb
$('form').hide();
$("<%= j render "userfollowships/product" %>").appendTo('body')

app/views/userfollowships/new.html.erb
<%= form_for [@boat,@follow], remote: true do |f| %>
<%= image_tag @boat.avatar(:medium) %>
<h1>Boat Name: <%= @boat.name %></h1>
<%= f.hidden_field :user_id,  value: "#{current_user.id}" %> 
<%= f.submit "Follow this Boat" %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Form</h1>
<%= form_for @user do |f| %>
<%= f.label :name %><br>
<%= f.text_field :name %>
<br>
<%= f.label :username %><br>
<%= f.text_field :username %>
<br>
<%= f.label :password %><br>
<%= f.password_field :password %>
<br>
<%= f.submit "Sign Up!" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%= @user.username %>!</h1>
<%= link_to "Add Your Boat", new_boat_path %>